### PR TITLE
Type change in axpy ElementWise Kernel

### PR DESCRIPTION
**Pull request by sidward**
This is a minor change. For some reason, when S was used, CuPy would throw a key error.

### CODE REVIEW

**Comment by chcodes** [comment]
The problem with this change is that new copies of alpha and lambda would be created each call, and turned into the same datatype as the other inputs. The other inputs are often complex valued while alpha/lambda are often not. I have some use cases where lambda is already a large array and turning it from float to complex would unnecessarily occupy valuable device memory.

**Comment by sidward** [comment]
Hm, I see. I get a dictionary key error when using cuda 10.2. Can I ask what version of cuda you're using?

**Comment by chcodes** [comment]
I'm using cuda 9.0 but I'm also getting a key error:

> Traceback (most recent call last):
>   File "test_device_placing.py", line 20, in <module>
>     util.axpy(y, a, x)
>   File "/hpf/projects/cmacgowan/chuynh/sigpy/sigpy/util.py", line 440, in axpy
>     _axpy_cuda(a, x, y)
>   File "cupy/core/_kernel.pyx", line 540, in cupy.core._kernel.ElementwiseKernel.__call__
>   File "cupy/core/_kernel.pyx", line 587, in cupy.core._kernel.ElementwiseKernel._decide_params_type
>   File "cupy/core/_kernel.pyx", line 299, in cupy.core._kernel._decide_params_type_core
> KeyError: 'S'

I actually also have a pull request open https://github.com/mikgroup/sigpy/pull/41 trying to address this problem. From what I understand, S is a datatype placeholder, which gives the cuda kernel flexibility in what the datatype should be. The kernel would determine what the datatype should be based on the datatypes of the arguments passed to it. But this error seems to occur whenever a Python scalar is passed to the kernel.

Right now my solution is to convert any scalars to arrays before passing them to these low level functions (axpy, soft_thresh, etc.). It seems inefficient to do the conversion inside these functions, since they are called hundreds of times, which would repeat the same conversion unnecessarily.

**Comment by sidward** [comment]
Hm. Apologies for not realizing your previous pull request was to address the same issue.

> The problem with this change is that new copies of alpha and lambda would be created each call, and turned into the same datatype as the other inputs.
>  I have some use cases where lambda is already a large array and turning it from float to complex would unnecessarily occupy valuable device memory.

Yes, but given that `axpy` expects a scalar and the function's scope ends at the return function, this shouldn't be much of a memory issue as fair as I know. However, conversion per iteration is more flops, so I agree that this is sub-optimal.

> I actually also have a pull request open #41 trying to address this problem. From what I understand, S is a datatype placeholder, which gives the cuda kernel flexibility in what the datatype should be. The kernel would determine what the datatype should be based on the datatypes of the arguments passed to it. But this error seems to occur whenever a Python scalar is passed to the kernel.

> Right now my solution is to convert any scalars to arrays before passing them to these low level functions (axpy, soft_thresh, etc.). It seems inefficient to do the conversion inside these functions, since they are called hundreds of times, which would repeat the same conversion unnecessarily.

I agree. Could you please also make the "T" change to the CuPy element wise kernels in `thresh.py` as in #42? I'll close this pull request as you've addressed everything else :)

**Comment by chcodes** [comment]
What's the reason for changing S to T?

**Comment by sidward** [comment]
To avoid the same key error when I can the threshold function.

**Comment by chcodes** [comment]
Changing it to T might not fix the problem. Can you look at this example I made? Maybe I did something wrong.

```python
import sigpy as sp
import numpy as np
import cupy as cp


# Original
_soft_thresh_cuda = cp.ElementwiseKernel(
    'S lamda, T input',
    'T output',
    """
    S abs_input = abs(input);
    T sign;
    if (abs_input == 0)
        sign = 0;
    else
        sign = input / (T) abs_input;
    S mag = abs_input - lamda;
    mag = (abs(mag) + mag) / 2.;

    output = (T) mag * sign;
    """,
    name='soft_thresh')


# Proposed change of S to T
_soft_thresh_cuda2 = cp.ElementwiseKernel(
    'T lamda, T input',
    'T output',
    """
    T abs_input = abs(input);
    T sign;
    if (abs_input == 0)
        sign = 0;
    else
        sign = input / (T) abs_input;
    T mag = abs_input - lamda;
    mag = (abs(mag) + mag) / 2.;

    output = (T) mag * sign;
    """,
    name='soft_thresh2')


device = 0
arr_shape = (24, 256, 512)

device = sp.Device(device)
xp = device.xp

# Create inputs
with device:
    x = sp.util.randn(arr_shape, dtype=xp.complex64, device=device)

    # lamda = 0.5
    # lamda = cp.array(0.5)
    lamda = cp.array(0.5, dtype=cp.complex64)

    # y = _soft_thresh_cuda(lamda, x)
    y = _soft_thresh_cuda2(lamda, x)  # Still gives error

```

**Comment by sidward** [comment]
I needed to add some casting to get the above code to work.

```
# Proposed change of S to T
_soft_thresh_cuda2 = cp.ElementwiseKernel(
    'T lamda, T input',
    'T output',
    """
    T abs_input = abs(input);
    T sign = 0;
    if (abs_input != (T) 0)
        sign = input / abs_input;
    T mag = abs_input - lamda;
    mag = (abs(mag) + mag) / (T) 2;
    output = mag * sign;
    """,
    name='soft_thresh2')
```

**Comment by chcodes** [comment]
Does your lamda need to be complex-valued? I found that it works for floats. And prior to the change here https://github.com/mikgroup/sigpy/commit/2416b7fa6fbd08ef46ac75273272f10ad2a3410a, lamda was always converted to floats.

**Comment by sidward** [comment]
With my branch, without changing S to T, I got the key 'S' error. I just pulled down your branch and tested it on my code, and I can confirm that I am not getting any errors. Please feel free to ignore my request!

**Comment by chcodes** [comment]
Wow great! I'll try not to mess up my branch in the meantime.

**Pull request closed without merging**
