### PR TITLE
Override saxpy/xpay from 31e013e

### PR DESCRIPTION
**Pull request by youngwook-mri**
Hey Frank,

TV recon with multi-gpu (tested on two Tesla P40) spits out the following:

`ValueError: Array device must be same as the current device: array device = 1 while current = 0`

I just grabbed the `saxpy` and `xpay` subroutines from v0.1.16 and overwrote the newer ones, and it works now. Not sure if you are aware of this..

Thanks,
Youngwook

### CODE REVIEW

**Comment by sidward** [comment]
Can you check this against #50 please?

**Comment by youngwook-mri** [comment]
Hi, with the changes that I overwrote, I did not run into the issue reported #50 both on single GPU and multiple GPU runs. I wonder if the issue is CUDA version specific. I'm running this in a Conda environment with CUDA 10.0 and python 3.7.9.

**Comment by cth7** [comment]
I think these changes look good. Your axpy (like the old old one) would also use less total memory.

I think `x` and `y` should be put on the same device outside of `axpy` though. With the new changes, `axpy` would 'auto correct' the fact that `x` and `y` aren't on the same device, which would encourage users to not be mindful of how many device transfers are being used, and overall slowing down performance.

**Comment by cth7** [comment]
To better support my argument... The CuPy add function also doesn't auto correct the fact that its two input arrays aren't on the same device. Exampe:

```python
import cupy as cp

import sigpy as sp


with sp.Device(0):
    x = cp.ones((2, 3))

with sp.Device(1):
    y = cp.ones((2, 3))


# Both of these would raise error saying that one of the input arrays
# is not on current device
with sp.Device(0):
    cp.add(x, y, out=y)

with sp.Device(1):
    cp.add(x, y, out=y)

```
```
ValueError: Array device must be same as the current device: array device = 1 while current = 0
```

**Comment by youngwook-mri** [comment]
Thanks @cth7 - good to know about the CuPy add function in multi-device usage.

**Pull request closed without merging**
